language: python
sudo: required
python:
  - "2.7"
  - "3.6"
install:
  - pip install defcon
  - pip install fonttools
  - pip install git+https://github.com/robofab-developers/fontPens.git
  - pip install coveralls
script:
  - cd Lib
  - coverage run --parallel-mode glyphConstructionBuilder.py
after_success:
  - coverage combine
  - coveralls